printWidth = 80
tabWidth = 2
useTabs = false
semi = false
singleQuote = false
quoteProps = "as-needed"
jsxSingleQuote = false
trailingComma = "none"
bracketSpacing = true
jsxBracketSameLine = false
arrowParens = "always"
endOfLine = "lf"
htmlWhitespaceSensitivity = "css"